### ISSUE TITLE
scenario outline that launches app cannot be first scenario

### ISSUE THREAD

**Issue by abbood** [Ahmed-Ali/Cucumberish#12]
# bug repro
`given` the fist scenario is a scenario outline (ie one that has a data table like so):

```
Feature: view user details
As a user I should be able to see all user details

Scenario Outline: displaying user rows
  Given the app is running
  When A table with rows of type "users" is displayed
  Then the row with text "<name>" shows up at index "<index>"

Examples:
|     name   | index |
|  Abdullah  |      0      |
|  Rima      |      1      |
|  Craig     |      2      |
```
`when` the user runs the tests
`then`
**expected** the app should launch and tests must be executed as normal
**actual** the app crashes with this error 
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

# related 
see this issue for more details https://github.com/Ahmed-Ali/Cucumberish/issues/11

# analysis
see this comment https://github.com/Ahmed-Ali/Cucumberish/issues/11#issuecomment-215328419

**Comment by Ahmed-Ali** [comment]
Hi @abbood 
There are two points worth highlighting:
1- The whole implementation of Cucumberish is written in Objective-C, which doesn't have the concept of "Optional unwrapping".
2- The actual implementation of the step that launches the app (or do anything else), is written by you!

The point is, there is something in your step implementation, and since I can not see any complete code snippet, I can not help that much!
