### ISSUE TITLE
Option for changing/disabling class prefix

### ISSUE THREAD

**Issue by brentleyjones** [Ahmed-Ali/Cucumberish#35]
Currently we prefix the test case names with `CCI`/`CCI_`. Can we have an option to disable that prefix and/or change it? For our use case we only use Cucumberish so we don't need the prefix, and it would make our reports look cleaner without them.

**Comment by Ahmed-Ali** [comment]
The prefix was added in the first place to avoid name conflicts with other existing classes.
I don't think disabling it completely is safe enough, but I will make it a variable so you can change it.

**Comment by Ahmed-Ali** [comment]
Pushed to develop and will be in master with the upcoming release.
See the featureNamesPrefix property of Cucumberish

**Comment by brentleyjones** [comment]
Cool. The change will work for us, since we will set it to `@""`, but for existing users it will be a slight regression, since it won't have a space or `_` (depending on pretty names setting).

**Comment by Ahmed-Ali** [comment]
Unless they have a custom report tool that makes use of the existing prefix (which is very low probability, I think), it should not be an issue. And if it turns out to be an issue, the fix should be easy to do.

For your case, I would recommend using an empty space, as it doesn't affect the beatified names you want and it helps avoid confusion. Of course this is completely up to you.
