### ISSUE TITLE
`beforeStart` and `afterFinish` should run in their own test cases

### ISSUE THREAD

**Issue by brentleyjones** [Ahmed-Ali/Cucumberish#37]
Currently `beforeStart` will run in the first test case, and `afterFinish` will run in the last test case (I think, I don't have an afterFinish hook). If these are long running (like they are for our setup) it will incorrectly inflate the running time of those test cases. If instead they became their own test case (like `[Hooks beforeStart]` and `[Hooks afterFinish]`) they will be reported on separately. Of course, we need to make sure the name doesn't clash, so maybe make it configurable.

**Comment by brentleyjones** [comment]
I'm going to take a stab at creating a PR for this.

**Comment by brentleyjones** [comment]
Before this I did #38. After that I'll think about this some more.

**Comment by Ahmed-Ali** [comment]
I would recommend reporting its crash as unhandled crash, better than adding two additional test cases. Because the "beforeStart" and "afterFinish" are not related to the features; they like the setup and tearDown in unit testing. Which doesn't show up anywhere in the execution report or test navigator.
