### ISSUE TITLE
Crash when Cucumberish is not able to read languagesFileContent

### ISSUE THREAD

**Issue by concertman** [Ahmed-Ali/Cucumberish#7]
I've not been able to figure out why it can't get the languages File Content but it is causing a crash

![screen_shot_2016-03-29_at_11_26_11](https://cloud.githubusercontent.com/assets/510749/14105134/960b00ee-f5a1-11e5-853e-eef39f3fe073.png)

### Update
Looks like `gherkinLanguagesBundle` is nil inside `- (NSDictionary<NSString *, GHGherkinLanguageSetting *> *)languagesSetting`

**Comment by BartBM** [comment]
I got the same error.
This happens when you try to add the Cucumberish library as a pod to an XCUI test target. 
You should add the folder directly to your test target as described on the wiki. (Note: I did NOT add the Cucumberish source directory as a reference but selected "Create groups", the opposite from what's mentioned on the wiki).

**Comment by Ahmed-Ali** [comment]
Maybe I mis communicated that. Adding cucumber as a reference means select as "Create groups" instead of "create folder reference". I will update that.
