### ISSUE TITLE
Has Xcode 9.2 has broken this project :(

### ISSUE THREAD

**Issue by DanielAsher** [Ahmed-Ali/Cucumberish#97]
#89 has not been addressed and now Xcode 9.2 refuses to run cucumberish tests altogether. Is there any solution to this?

**Comment by dgommers** [comment]
The screenshot you posted in #89 shows that you are running them on your local Mac. For me they work once I switch to a simulated iOS device. Does that also work for you? 

It looks like it is not able to find the feature files on Mac since the bundle structure is different. I am checking if there is a way to fix this up.

**Comment by dgommers** [comment]
@DanielAsher is it working for you now #98 is merged?
